# Generated by Django 4.2.5 on 2023-10-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bankapp', '0002_remove_branch_district_delete_basicdetails_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=250)),
                ('DOB', models.DateField(default=None)),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(default=None, max_length=1)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Phonenumber', models.IntegerField(default=250)),
                ('Address', models.CharField(default=None, max_length=250)),
                ('District', models.CharField(max_length=250)),
                ('Branch', models.CharField(max_length=250)),
                ('Country', models.CharField(default='India', max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('Pincode', models.IntegerField()),
            ],
        ),
    ]
