# Generated by Django 4.2.5 on 2023-10-04 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='basicdetails',
            name='Country',
        ),
        migrations.AddField(
            model_name='basicdetails',
            name='Accounttype',
            field=models.CharField(choices=[('Savings account', 'Savings account'), ('Current account', 'Current account')], default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='Phonenumber',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankapp.district')),
            ],
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='Branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.branches'),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='District',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district'),
        ),
    ]
