# Generated by Django 4.2.5 on 2023-10-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0004_district_remove_basicdetails_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='Gender',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
