# Generated by Django 4.2.5 on 2023-10-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0005_alter_basicdetails_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=250)),
                ('DOB', models.DateField()),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(default=None, max_length=250)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Phonenumber', models.PositiveIntegerField(default=0)),
                ('Address', models.CharField(default=None, max_length=250)),
                ('State', models.CharField(max_length=250)),
                ('Pincode', models.PositiveIntegerField()),
                ('Accounttype', models.CharField(choices=[('Savings account', 'Savings account'), ('Current account', 'Current account')], default=None, max_length=250)),
                ('Materials_provided', models.CharField(max_length=250)),
                ('Branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.branches')),
                ('District', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bankapp.district')),
            ],
        ),
        migrations.DeleteModel(
            name='BasicDetails',
        ),
    ]
