# Generated by Django 4.2.5 on 2023-10-04 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0006_applicationform_delete_basicdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ApplicationForm',
            new_name='Application',
        ),
    ]
