# Generated by Django 4.2.5 on 2023-10-04 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bankapp', '0007_rename_applicationform_application'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='Accounttype',
            new_name='accounttype',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Branch',
            new_name='branch',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='District',
            new_name='district',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Materials_provided',
            new_name='materials_provided',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='Pincode',
            new_name='pincode',
        ),
        migrations.RenameField(
            model_name='application',
            old_name='State',
            new_name='state',
        ),
    ]
